package PaooGame.Database;

import com.sun.security.jgss.GSSUtil;
import oracle.jdbc.proxy.annotation.Pre;

import java.io.BufferedReader;
import java.io.FileReader;
import java.io.IOException;
import java.sql.*;
import java.util.ArrayList;
import java.util.List;
import java.util.concurrent.ExecutorService;
import java.util.concurrent.Executors;

public class Database {
    public DatabaseManager db;

    public Database(){
        this.db = DatabaseManager.getInstance();
    }
    public boolean connect(){

        if(db.connection != null) {
            if (db.isOracleDatabase == false) {
                return (db.connect() != null);
            } else {
                System.out.println("Connected already to the database !!!");
                return true;
            }
        }
        return (db.connect() != null);
    }

    public boolean isConnected(){
        return (db.connection != null);
    }
    public void disconnect(){
//        db.disconnect();
        //System.out.println("Disconnecting...");
        db.disconnect();
    }

    public int[][] loadCollisionMap1(int width , int height){
        String path = "res/maps/collision/map1.txt";

        int [][] map = new int[height][width];
        int [][] tiles=new int[width][height];
        String line;
        int row = 0;

        try {

            String sql =null;
            Statement stm = null;
//            sql = "DROP TABLE MAP1";

            stm = db.connection.createStatement();
            //stm.executeUpdate(sql);

            if(db.isOracleDatabase) {
                //mai intai stergem
                sql = "BEGIN " +
                        "   EXECUTE IMMEDIATE 'DROP TABLE CollisionMAP1'; " +
                        "EXCEPTION " +
                        "   WHEN OTHERS THEN " +
                        "      IF SQLCODE != -942 THEN RAISE; END IF; " +
                        "END;";
                stm.execute(sql);

                sql = "CREATE TABLE CollisionMAP1 " +
                        "(ID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY," +
                        "LINIE NUMBER NOT NULL,"
                        + "COLOANA NUMBER NOT NULL," +
                        "VALUE NUMBER NOT NULL)";
            }
            else{
                sql = "DROP TABLE IF EXISTS CollisionMAP1";
                stm.execute(sql);

                System.out.println("CollisionMAP1 Deleted !!!");
                sql = "CREATE TABLE IF NOT EXISTS CollisionMAP1 " +
                        "(ID INTEGER PRIMARY KEY AUTOINCREMENT," +
                        "LINIE INTEGER NOT NULL,"
                        + "COLOANA INTEGER NOT NULL," +
                        "VALUE INTEGER NOT NULL)";
            }
//            stm = db.connection.createStatement();
            int delay = 50000;
            while((delay--) !=0);

            stm.executeUpdate(sql);
            stm.close();
        }
        catch (SQLException e){
            System.out.println("Error creating MAP1 -> "+e.getMessage());
        }
        try {

//            System.out.println("Trying to open file with FileReader...");
            FileReader fr = new FileReader(path);
//            System.out.println("FileReader opened successfully.");
            BufferedReader reader = new BufferedReader(fr);

            while((line = reader.readLine()) != null && row <height){
                line = line.trim(); //elimina spatiile de la inceput si sfarsit
                if(line.isEmpty()) continue;

                String [] element = line.split("\\s+");
                for(int i=0;i<width;i++)
                {
                    map[row][i] = Integer.parseInt(element[i]);
                }

                row++;
            }
            for (int i = 0; i < height; i++) {
                for (int j = 0; j < width; j++) {
                    tiles[j][i] = map[i][j];
                }
            }

            reader.close();
        }
        catch (IOException e)
        {
            System.out.println("Text file ThematicMap couldn't be opened");
        }

        try{

            for(int i=0;i<map.length;i++){
                for(int j=0;j<map[i].length;j++){
                    String sql = "INSERT INTO CollisionMAP1 (LINIE,COLOANA,VALUE) VALUES ("+i+","+j+","+map[i][j]+")";
                    Statement stm = null;
                    stm = db.connection.createStatement();
                    stm.executeUpdate(sql);
                    stm.close();
                }
            }
        }catch (SQLException e){
            System.out.println("Error loading MAP1 -> "+e.getMessage());
        }
        return map;
    }
    public int[][] loadThematicMap1(int width , int height){
        String path = "res/maps/thematic/map1.txt";

        int [][] map = new int[height][width];
        int [][] tiles=new int[width][height];
        String line;
        int row = 0;

        try {
            String sql =null;
            Statement stm = null;
//            sql = "DROP TABLE MAP1";
//
            stm = db.connection.createStatement();
//            stm.executeUpdate(sql);
            if(db.isOracleDatabase) {
                sql = "BEGIN " +
                        "   EXECUTE IMMEDIATE 'DROP TABLE MAP1'; " +
                        "EXCEPTION " +
                        "   WHEN OTHERS THEN " +
                        "      IF SQLCODE != -942 THEN RAISE; END IF; " +
                        "END;";
                stm.execute(sql);

                sql = "CREATE TABLE MAP1 " +
                        "(ID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY," +
                        "LINIE NUMBER NOT NULL,"
                        + "COLOANA NUMBER NOT NULL," +
                        "VALUE NUMBER NOT NULL)";
            }
            else{
                sql = "DROP TABLE IF EXISTS MAP1";
                stm.execute(sql);

                sql = "CREATE TABLE IF NOT EXISTS MAP1 " +
                        "(ID INTEGER PRIMARY KEY AUTOINCREMENT," +
                        "LINIE INTEGER NOT NULL,"
                        + "COLOANA INTEGER NOT NULL," +
                        "VALUE INTEGER NOT NULL)";
            }
//            stm = db.connection.createStatement();
            int delay = 50000;
            while((delay--) !=0);

            stm.executeUpdate(sql);
            stm.close();
        }
        catch (SQLException e){
            System.out.println("Error creating MAP1 -> "+e.getMessage());
        }
        try {
//            System.out.println("Trying to open file with FileReader...");
            FileReader fr = new FileReader(path);
//            System.out.println("FileReader opened successfully.");
            BufferedReader reader = new BufferedReader(fr);

            while((line = reader.readLine()) != null && row <height){
                line = line.trim(); //elimina spatiile de la inceput si sfarsit
                if(line.isEmpty()) continue;

                String [] element = line.split("\\s+");
                for(int i=0;i<width;i++)
                {
                    map[row][i] = Integer.parseInt(element[i]);
                }

                row++;
            }
            for (int i = 0; i < height; i++) {
                for (int j = 0; j < width; j++) {
                    tiles[j][i] = map[i][j];
                }
            }

            reader.close();
        }
        catch (IOException e)
        {
            System.out.println("Text file ThematicMap couldn't be opened");
        }

        try{
            for(int i=0;i<map.length;i++){
                for(int j=0;j<map[i].length;j++){
                    String sql = "INSERT INTO MAP1 (LINIE,COLOANA,VALUE) VALUES ("+i+","+j+","+map[i][j]+")";
                    Statement stm = null;
                    stm = db.connection.createStatement();
                    stm.executeUpdate(sql);
                    stm.close();
                }
            }
        }catch (SQLException e){
            System.out.println("Error loading MAP1 -> "+e.getMessage());
        }
        return map;
    }
    public boolean isOracleDatabase(){
        return db.isOracleDatabase;
    }


    public int[][] downloadCollisionMap1(){

        int height=0,width=0;
        try(Statement stmt = db.connection.createStatement()){
            System.out.println("Downloading CollisionMAP1 from database...");
            String querySize = "SELECT MAX(LINIE) AS maxLine , MAX(COLOANA) AS maxCol FROM MAP1 ";
            try (ResultSet rs = stmt.executeQuery(querySize)) {
                if (rs.next()) {
                    height = rs.getInt("maxLine") + 1;
                    width = rs.getInt("maxCol") + 1;
                }
            }

            int[][] map = new int[height][width];
            String query = "SELECT LINIE,COLOANA , VALUE FROM CollisionMAP1";
            try (ResultSet rs = stmt.executeQuery(query)) {
                while (rs.next()) {
                    int linie = rs.getInt("LINIE");
                    int coloana = rs.getInt("COLOANA");
                    int value = rs.getInt("VALUE");
                    map[linie][coloana] = value;
                }
            }
            return map;

        }catch (SQLException e){
            e.printStackTrace();
            return null;
        }
    }
    public int[][] downloadThematicMap1(){
        //verfiyConnectionToOracleDatabase();
        int height=0,width=0;
        try(Statement stmt = db.connection.createStatement()){
            System.out.println("Downloading MAP1 from database...");
            String querySize = "SELECT MAX(LINIE) AS maxLine , MAX(COLOANA) AS maxCol FROM MAP1 ";
            try (ResultSet rs = stmt.executeQuery(querySize)) {
                if (rs.next()) {
                    height = rs.getInt("maxLine") + 1;
                    width = rs.getInt("maxCol") + 1;
                }
            }

            int[][] map = new int[height][width];
            String query = "SELECT LINIE,COLOANA , VALUE FROM MAP1";
            try (ResultSet rs = stmt.executeQuery(query)) {
                while (rs.next()) {
                    int linie = rs.getInt("LINIE");
                    int coloana = rs.getInt("COLOANA");
                    int value = rs.getInt("VALUE");
                    map[linie][coloana] = value;
                }
            }
            return map;

        }catch (SQLException e){
            e.printStackTrace();
            return null;
        }
    }

    public int[][] loadCollisionMap2(int width , int height){
        String path = "res/maps/collision/map2.txt";

        int [][] map = new int[height][width];
        int [][] tiles=new int[width][height];
        String line;
        int row = 0;

        try {

            String sql =null;
            Statement stm = null;
//            sql = "DROP TABLE MAP1";

            stm = db.connection.createStatement();
            //stm.executeUpdate(sql);

            if(db.isOracleDatabase) {
                //mai intai stergem
                sql = "BEGIN " +
                        "   EXECUTE IMMEDIATE 'DROP TABLE CollisionMAP2'; " +
                        "EXCEPTION " +
                        "   WHEN OTHERS THEN " +
                        "      IF SQLCODE != -942 THEN RAISE; END IF; " +
                        "END;";
                stm.execute(sql);

                sql = "CREATE TABLE CollisionMAP2 " +
                        "(ID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY," +
                        "LINIE NUMBER NOT NULL,"
                        + "COLOANA NUMBER NOT NULL," +
                        "VALUE NUMBER NOT NULL)";
            }
            else{
                sql = "DROP TABLE IF EXISTS CollisionMAP2";
                stm.execute(sql);

                System.out.println("CollisionMAP2 Deleted !!!");
                sql = "CREATE TABLE IF NOT EXISTS CollisionMAP2 " +
                        "(ID INTEGER PRIMARY KEY AUTOINCREMENT," +
                        "LINIE INTEGER NOT NULL,"
                        + "COLOANA INTEGER NOT NULL," +
                        "VALUE INTEGER NOT NULL)";
            }
//            stm = db.connection.createStatement();
            int delay = 50000;
            while((delay--) !=0);

            stm.executeUpdate(sql);
            stm.close();
        }
        catch (SQLException e){
            System.out.println("Error creating CollisionMAP2 -> "+e.getMessage());
        }
        try {

//            System.out.println("Trying to open file with FileReader...");
            FileReader fr = new FileReader(path);
//            System.out.println("FileReader opened successfully.");
            BufferedReader reader = new BufferedReader(fr);

            while((line = reader.readLine()) != null && row <height){
                line = line.trim(); //elimina spatiile de la inceput si sfarsit
                if(line.isEmpty()) continue;

                String [] element = line.split("\\s+");
                for(int i=0;i<width;i++)
                {
                    map[row][i] = Integer.parseInt(element[i]);
                }

                row++;
            }
            for (int i = 0; i < height; i++) {
                for (int j = 0; j < width; j++) {
                    tiles[j][i] = map[i][j];
                }
            }

            reader.close();
        }
        catch (IOException e)
        {
            System.out.println("Text file ThematicMap couldn't be opened");
        }

        try{

            for(int i=0;i<map.length;i++){
                for(int j=0;j<map[i].length;j++){
                    String sql = "INSERT INTO CollisionMAP2 (LINIE,COLOANA,VALUE) VALUES ("+i+","+j+","+map[i][j]+")";
                    Statement stm = null;
                    stm = db.connection.createStatement();
                    stm.executeUpdate(sql);
                    stm.close();
                }
            }
        }catch (SQLException e){
            System.out.println("Error loading MAP2 -> "+e.getMessage());
        }
        return map;
    }
    public int[][] loadThematicMap2(int width , int height){
        String path = "res/maps/thematic/map2.txt";

        int [][] map = new int[height][width];
        int [][] tiles=new int[width][height];
        String line;
        int row = 0;

        try {
            String sql =null;
            Statement stm = null;
//            sql = "DROP TABLE MAP1";
//
            stm = db.connection.createStatement();
//            stm.executeUpdate(sql);
            if(db.isOracleDatabase) {
                sql = "BEGIN " +
                        "   EXECUTE IMMEDIATE 'DROP TABLE MAP2'; " +
                        "EXCEPTION " +
                        "   WHEN OTHERS THEN " +
                        "      IF SQLCODE != -942 THEN RAISE; END IF; " +
                        "END;";
                stm.execute(sql);

                sql = "CREATE TABLE MAP2 " +
                        "(ID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY," +
                        "LINIE NUMBER NOT NULL,"
                        + "COLOANA NUMBER NOT NULL," +
                        "VALUE NUMBER NOT NULL)";
            }
            else{
                sql = "DROP TABLE IF EXISTS MAP2";
                stm.execute(sql);

                sql = "CREATE TABLE IF NOT EXISTS MAP2 " +
                        "(ID INTEGER PRIMARY KEY AUTOINCREMENT," +
                        "LINIE INTEGER NOT NULL,"
                        + "COLOANA INTEGER NOT NULL," +
                        "VALUE INTEGER NOT NULL)";
            }
//            stm = db.connection.createStatement();
            int delay = 50000;
            while((delay--) !=0);

            stm.executeUpdate(sql);
            stm.close();
        }
        catch (SQLException e){
            System.out.println("Error creating MAP2 -> "+e.getMessage());
        }
        try {
//            System.out.println("Trying to open file with FileReader...");
            FileReader fr = new FileReader(path);
//            System.out.println("FileReader opened successfully.");
            BufferedReader reader = new BufferedReader(fr);

            while((line = reader.readLine()) != null && row <height){
                line = line.trim(); //elimina spatiile de la inceput si sfarsit
                if(line.isEmpty()) continue;

                String [] element = line.split("\\s+");
                for(int i=0;i<width;i++)
                {
                    map[row][i] = Integer.parseInt(element[i]);
                }

                row++;
            }
            for (int i = 0; i < height; i++) {
                for (int j = 0; j < width; j++) {
                    tiles[j][i] = map[i][j];
                }
            }

            reader.close();
        }
        catch (IOException e)
        {
            System.out.println("Text file ThematicMap couldn't be opened");
        }

        try{
            for(int i=0;i<map.length;i++){
                for(int j=0;j<map[i].length;j++){
                    String sql = "INSERT INTO MAP2 (LINIE,COLOANA,VALUE) VALUES ("+i+","+j+","+map[i][j]+")";
                    Statement stm = null;
                    stm = db.connection.createStatement();
                    stm.executeUpdate(sql);
                    stm.close();
                }
            }
        }catch (SQLException e){
            System.out.println("Error loading MAP2 -> "+e.getMessage());
        }
        return map;
    }

    public int[][] downloadCollisionMap2(){

        int height=0,width=0;
        try(Statement stmt = db.connection.createStatement()){
            System.out.println("Downloading CollisionMAP2 from database...");
            String querySize = "SELECT MAX(LINIE) AS maxLine , MAX(COLOANA) AS maxCol FROM CollisionMAP2 ";
            try (ResultSet rs = stmt.executeQuery(querySize)) {
                if (rs.next()) {
                    height = rs.getInt("maxLine") + 1;
                    width = rs.getInt("maxCol") + 1;
                }
            }

            int[][] map = new int[height][width];
            String query = "SELECT LINIE,COLOANA , VALUE FROM CollisionMAP2";
            try (ResultSet rs = stmt.executeQuery(query)) {
                while (rs.next()) {
                    int linie = rs.getInt("LINIE");
                    int coloana = rs.getInt("COLOANA");
                    int value = rs.getInt("VALUE");
                    map[linie][coloana] = value;
                }
            }
            return map;

        }catch (SQLException e){
            e.printStackTrace();
            return null;
        }
    }
    public int[][] downloadThematicMap2(){
        //verfiyConnectionToOracleDatabase();
        int height=0,width=0;
        try(Statement stmt = db.connection.createStatement()){
            System.out.println("Downloading MAP2 from database...");
            String querySize = "SELECT MAX(LINIE) AS maxLine , MAX(COLOANA) AS maxCol FROM MAP2 ";
            try (ResultSet rs = stmt.executeQuery(querySize)) {
                if (rs.next()) {
                    height = rs.getInt("maxLine") + 1;
                    width = rs.getInt("maxCol") + 1;
                }
            }

            int[][] map = new int[height][width];
            String query = "SELECT LINIE,COLOANA , VALUE FROM MAP2";
            try (ResultSet rs = stmt.executeQuery(query)) {
                while (rs.next()) {
                    int linie = rs.getInt("LINIE");
                    int coloana = rs.getInt("COLOANA");
                    int value = rs.getInt("VALUE");
                    map[linie][coloana] = value;
                }
            }
            return map;

        }catch (SQLException e){
            e.printStackTrace();
            return null;
        }
    }
    public int[][] loadCollisionMap3(int width , int height){
        String path = "res/maps/collision/map3.txt";

        int [][] map = new int[height][width];
        int [][] tiles=new int[width][height];
        String line;
        int row = 0;

        try {

            String sql =null;
            Statement stm = null;
//            sql = "DROP TABLE MAP1";

            stm = db.connection.createStatement();
            //stm.executeUpdate(sql);

            if(db.isOracleDatabase) {
                //mai intai stergem
                sql = "BEGIN " +
                        "   EXECUTE IMMEDIATE 'DROP TABLE CollisionMAP3'; " +
                        "EXCEPTION " +
                        "   WHEN OTHERS THEN " +
                        "      IF SQLCODE != -942 THEN RAISE; END IF; " +
                        "END;";
                stm.execute(sql);

                sql = "CREATE TABLE CollisionMAP3 " +
                        "(ID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY," +
                        "LINIE NUMBER NOT NULL,"
                        + "COLOANA NUMBER NOT NULL," +
                        "VALUE NUMBER NOT NULL)";
            }
            else{
                sql = "DROP TABLE IF EXISTS CollisionMAP3";
                stm.execute(sql);

                System.out.println("CollisionMAP3 Deleted !!!");
                sql = "CREATE TABLE IF NOT EXISTS CollisionMAP3 " +
                        "(ID INTEGER PRIMARY KEY AUTOINCREMENT," +
                        "LINIE INTEGER NOT NULL,"
                        + "COLOANA INTEGER NOT NULL," +
                        "VALUE INTEGER NOT NULL)";
            }
//            stm = db.connection.createStatement();
            int delay = 50000;
            while((delay--) !=0);

            stm.executeUpdate(sql);
            stm.close();
        }
        catch (SQLException e){
            System.out.println("Error creating CollisionMAP3 -> "+e.getMessage());
        }
        try {

//            System.out.println("Trying to open file with FileReader...");
            FileReader fr = new FileReader(path);
//            System.out.println("FileReader opened successfully.");
            BufferedReader reader = new BufferedReader(fr);

            while((line = reader.readLine()) != null && row <height){
                line = line.trim(); //elimina spatiile de la inceput si sfarsit
                if(line.isEmpty()) continue;

                String [] element = line.split("\\s+");
                for(int i=0;i<width;i++)
                {
                    map[row][i] = Integer.parseInt(element[i]);
                }

                row++;
            }
            for (int i = 0; i < height; i++) {
                for (int j = 0; j < width; j++) {
                    tiles[j][i] = map[i][j];
                }
            }

            reader.close();
        }
        catch (IOException e)
        {
            System.out.println("Text file ThematicMap couldn't be opened");
        }

        try{

            for(int i=0;i<map.length;i++){
                for(int j=0;j<map[i].length;j++){
                    String sql = "INSERT INTO CollisionMAP3 (LINIE,COLOANA,VALUE) VALUES ("+i+","+j+","+map[i][j]+")";
                    Statement stm = null;
                    stm = db.connection.createStatement();
                    stm.executeUpdate(sql);
                    stm.close();
                }
            }
        }catch (SQLException e){
            System.out.println("Error loading CollisionMAP3 -> "+e.getMessage());
        }
        return map;
    }
    public int[][] loadThematicMap3(int width , int height){
        String path = "res/maps/thematic/map3.txt";

        int [][] map = new int[height][width];
        int [][] tiles=new int[width][height];
        String line;
        int row = 0;

        try {
            String sql =null;
            Statement stm = null;
//            sql = "DROP TABLE MAP1";
//
            stm = db.connection.createStatement();
//            stm.executeUpdate(sql);
            if(db.isOracleDatabase) {
                sql = "BEGIN " +
                        "   EXECUTE IMMEDIATE 'DROP TABLE MAP3'; " +
                        "EXCEPTION " +
                        "   WHEN OTHERS THEN " +
                        "      IF SQLCODE != -942 THEN RAISE; END IF; " +
                        "END;";
                stm.execute(sql);

                sql = "CREATE TABLE MAP3 " +
                        "(ID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY," +
                        "LINIE NUMBER NOT NULL,"
                        + "COLOANA NUMBER NOT NULL," +
                        "VALUE NUMBER NOT NULL)";
            }
            else{
                sql = "DROP TABLE IF EXISTS MAP3";
                stm.execute(sql);

                sql = "CREATE TABLE IF NOT EXISTS MAP3 " +
                        "(ID INTEGER PRIMARY KEY AUTOINCREMENT," +
                        "LINIE INTEGER NOT NULL,"
                        + "COLOANA INTEGER NOT NULL," +
                        "VALUE INTEGER NOT NULL)";
            }
//            stm = db.connection.createStatement();
            int delay = 50000;
            while((delay--) !=0);

            stm.executeUpdate(sql);
            stm.close();
        }
        catch (SQLException e){
            System.out.println("Error creating MAP3 -> "+e.getMessage());
        }
        try {
//            System.out.println("Trying to open file with FileReader...");
            FileReader fr = new FileReader(path);
//            System.out.println("FileReader opened successfully.");
            BufferedReader reader = new BufferedReader(fr);

            while((line = reader.readLine()) != null && row <height){
                line = line.trim(); //elimina spatiile de la inceput si sfarsit
                if(line.isEmpty()) continue;

                String [] element = line.split("\\s+");
                for(int i=0;i<width;i++)
                {
                    map[row][i] = Integer.parseInt(element[i]);
                }

                row++;
            }
            for (int i = 0; i < height; i++) {
                for (int j = 0; j < width; j++) {
                    tiles[j][i] = map[i][j];
                }
            }

            reader.close();
        }
        catch (IOException e)
        {
            System.out.println("Text file ThematicMap couldn't be opened");
        }

        try{
            for(int i=0;i<map.length;i++){
                for(int j=0;j<map[i].length;j++){
                    String sql = "INSERT INTO MAP3 (LINIE,COLOANA,VALUE) VALUES ("+i+","+j+","+map[i][j]+")";
                    Statement stm = null;
                    stm = db.connection.createStatement();
                    stm.executeUpdate(sql);
                    stm.close();
                }
            }
        }catch (SQLException e){
            System.out.println("Error loading MAP3 -> "+e.getMessage());
        }
        return map;
    }

    public int[][] downloadCollisionMap3(){

        int height=0,width=0;
        try(Statement stmt = db.connection.createStatement()){
            System.out.println("Downloading CollisionMAP3 from database...");
            String querySize = "SELECT MAX(LINIE) AS maxLine , MAX(COLOANA) AS maxCol FROM CollisionMAP3 ";
            try (ResultSet rs = stmt.executeQuery(querySize)) {
                if (rs.next()) {
                    height = rs.getInt("maxLine") + 1;
                    width = rs.getInt("maxCol") + 1;
                }
            }

            int[][] map = new int[height][width];
            String query = "SELECT LINIE,COLOANA , VALUE FROM CollisionMAP3";
            try (ResultSet rs = stmt.executeQuery(query)) {
                while (rs.next()) {
                    int linie = rs.getInt("LINIE");
                    int coloana = rs.getInt("COLOANA");
                    int value = rs.getInt("VALUE");
                    map[linie][coloana] = value;
                }
            }
            return map;

        }catch (SQLException e){
            e.printStackTrace();
            return null;
        }
    }
    public int[][] downloadThematicMap3(){
        //verfiyConnectionToOracleDatabase();
        int height=0,width=0;
        try(Statement stmt = db.connection.createStatement()){
            System.out.println("Downloading MAP3 from database...");
            String querySize = "SELECT MAX(LINIE) AS maxLine , MAX(COLOANA) AS maxCol FROM MAP3 ";
            try (ResultSet rs = stmt.executeQuery(querySize)) {
                if (rs.next()) {
                    height = rs.getInt("maxLine") + 1;
                    width = rs.getInt("maxCol") + 1;
                }
            }

            int[][] map = new int[height][width];
            String query = "SELECT LINIE,COLOANA , VALUE FROM MAP3";
            try (ResultSet rs = stmt.executeQuery(query)) {
                while (rs.next()) {
                    int linie = rs.getInt("LINIE");
                    int coloana = rs.getInt("COLOANA");
                    int value = rs.getInt("VALUE");
                    map[linie][coloana] = value;
                }
            }
            return map;

        }catch (SQLException e){
            e.printStackTrace();
            return null;
        }
    }

    public void createPlayersTable()
    {
        if(isOracleDatabase()) {
            String sql = """
                    BEGIN
                        EXECUTE IMMEDIATE '
                            CREATE TABLE players (
                                id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
                                username VARCHAR2(50) UNIQUE NOT NULL,
                                password VARCHAR2(50) NOT NULL,
                                score NUMBER DEFAULT 0
                            )
                        ';
                    EXCEPTION
                        WHEN OTHERS THEN
                            IF SQLCODE != -955 THEN -- -955 = table already exists
                                RAISE;
                            END IF;
                    END;
                    """;

            try (Statement stmt = db.connection.createStatement()) {
                stmt.execute(sql);
                System.out.println("Players table created successfully (Oracle).");
            } catch (SQLException e) {
                e.printStackTrace();
            }
        }
        else
        {
            String sql = """
            CREATE TABLE IF NOT EXISTS players (
                id INTEGER PRIMARY KEY AUTOINCREMENT,
                username TEXT UNIQUE NOT NULL,
                password TEXT NOT NULL,
                score INTEGER DEFAULT 0
            );
            """;

            try(Statement stmt = db.connection.createStatement()){
                stmt.execute(sql);
                System.out.println("Players table created successfully.");
            }catch (SQLException e){
                e.printStackTrace();
            }
        }

    }

    public boolean usernameExists(String username)
    {
        String sql = "SELECT 1 FROM players WHERE username = ? FETCH FIRST ROWS ONLY";

        try(PreparedStatement pstmt = db.connection.prepareStatement(sql))
        {
            pstmt.setString(1, username);
            try(ResultSet rs = pstmt.executeQuery())
            {
                return rs.next(); // daca exista un rezultat , inseamna ca username-ul exista deja
            }
        }
        catch (SQLException e)
        {
            e.printStackTrace();
        }
        return false;
    }

    public boolean insertPlayer(String username,String password)
    {
        if (usernameExists(username)) {
            System.out.println("Username-ul există deja. Alege altul.");
            return false;
        }

        String sql = "INSERT INTO players(username, password) VALUES(?, ?)";

        try(PreparedStatement pstmt = db.connection.prepareStatement(sql))
        {
            pstmt.setString(1, username);
            pstmt.setString(2, password);
            pstmt.executeUpdate();
            System.out.println("Player inserted successfully.");
            return true;
        }
        catch (SQLException e)
        {
            e.printStackTrace();
        }
        return false;
    }

    public boolean verifyCredentials(String username,String password)
    {
        String query = "SELECT 1 FROM players WHERE username = ? AND password = ?";

        try{
            PreparedStatement pstmt = db.connection.prepareStatement(query);

            pstmt.setString(1, username);
            pstmt.setString(2, password);

            ResultSet rs = pstmt.executeQuery();

            return rs.next() ;  // true daca s-a gasit o potrivire

        }
        catch (SQLException e)
        {
            e.printStackTrace();
        }
        return false;
    }


    public void createLevelsTable()
    {
        if(isOracleDatabase()) {
            String sql = """
            BEGIN
                EXECUTE IMMEDIATE '
                    CREATE TABLE levels (
                        id NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
                        player_id NUMBER,
                        level_number NUMBER,
                        completed NUMBER(1) DEFAULT 0,
                        timer NUMBER,
                        score NUMBER,
                        CONSTRAINT fk_player FOREIGN KEY (player_id) REFERENCES players(id),
                        CONSTRAINT unique_level_per_player UNIQUE (player_id, level_number)
                    )
                ';
            EXCEPTION
                WHEN OTHERS THEN
                    IF SQLCODE != -955 THEN -- ORA-00955: name is already used by an existing object
                        RAISE;
                    END IF;
            END;
            """;

            try (Statement stmt = db.connection.createStatement()) {
                stmt.execute(sql);
                System.out.println("Levels table created successfully in Oracle.");
            } catch (SQLException e) {
                e.printStackTrace();
            }
        }
        else {
            String sql = """
                    CREATE TABLE IF NOT EXISTS levels (
                        id INTEGER PRIMARY KEY AUTOINCREMENT,
                        player_id INTEGER,
                        level_number INTEGER,
                        completed BOOLEAN DEFAULT 0,
                        timer INTEGER,
                        score INTEGER,
                        FOREIGN KEY(player_id) REFERENCES players(id),
                        UNIQUE(player_id, level_number)
                    );
                    """;

            try (Statement stmt = db.connection.createStatement()) {
                stmt.execute(sql);
                System.out.println("Levels table created successfully.");
            } catch (SQLException e) {
                e.printStackTrace();
            }
        }
    }

    private int getPlayerId(String username , String password)
    {
        String sqlPlayer = "SELECT id FROM players WHERE username = ? AND password = ?";
        try{
            PreparedStatement pstmt = db.connection.prepareStatement(sqlPlayer);
            pstmt.setString(1, username);
            pstmt.setString(2, password);
            ResultSet rs = pstmt.executeQuery();
            if(rs.next())
                return rs.getInt("id");
            else
                return -1;
        }
        catch (SQLException e)
        {
            e.printStackTrace();
        }
        return 0;
    }

    public void insertDefaultLevelsForPlayer(String username , String password) {
        int playerId = getPlayerId(username,password);
        String sql = "INSERT INTO levels (player_id, level_number, completed) VALUES (?, ?, 0)";
        try (PreparedStatement stmt = db.connection.prepareStatement(sql)) {
            for (int i = 1; i <= 3; i++) {
                stmt.setInt(1, playerId);
                stmt.setInt(2, i);
                stmt.addBatch();
            }
            stmt.executeBatch();
        } catch (SQLException e) {
            e.printStackTrace();
        }
    }
    public void insertLevel(String username, String password , int levelNumber , int timer , int score )
    {
//        if(levelNumber == 1)
//        {
//            insertDefaultLevelsForPlayer(getPlayerId(username,password));
//        }

        int playerId = getPlayerId(username,password);

        if(isOracleDatabase())
        {
            String sql = """
            MERGE INTO levels l
            USING (SELECT ? AS player_id, ? AS level_number FROM dual) src
            ON (l.player_id = src.player_id AND l.level_number = src.level_number)
            WHEN MATCHED THEN
                UPDATE SET completed = 1, timer = ?, score = ?
            WHEN NOT MATCHED THEN
                INSERT (player_id, level_number, completed, timer, score)
                VALUES (?, ?, 1, ?, ?)
            """;

            try (PreparedStatement pstmt = db.connection.prepareStatement(sql)) {
                pstmt.setInt(1, playerId);
                pstmt.setInt(2, levelNumber);
                pstmt.setInt(3, timer);
                pstmt.setInt(4, score);
                pstmt.setInt(5, playerId);
                pstmt.setInt(6, levelNumber);
                pstmt.setInt(7, timer);
                pstmt.setInt(8, score);

                pstmt.executeUpdate();
                System.out.println("S-a inserat sau actualizat cu succes datele pentru nivelul: " + levelNumber);
            } catch (SQLException e) {
                e.printStackTrace();
            }
        }
        else {


            try {
                String sql = """
                        INSERT OR REPLACE INTO levels (player_id, level_number, completed, timer, score) VALUES (?, ?, ?, ?, ?)
                        """;
                PreparedStatement pstmt = db.connection.prepareStatement(sql);

                pstmt.setInt(1, playerId);
                pstmt.setInt(2, levelNumber);
                pstmt.setBoolean(3, true);
                pstmt.setInt(4, timer);
                pstmt.setInt(5, score);

                pstmt.executeUpdate();

                System.out.println("S-a inserat cu succes datele de pe nivelul : " + levelNumber);
            } catch (SQLException e) {
                e.printStackTrace();
            }
        }
    }

    public int getNextMapNumber(String username, String password)
    {
        int playerId = getPlayerId(username,password);

        String sql = "";
        if(isOracleDatabase())
        {
            sql = """
            SELECT level_number 
            FROM levels 
            WHERE player_id = ? AND completed = 0 
            ORDER BY level_number ASC 
            FETCH FIRST 1 ROWS ONLY
        """;
        }
        else {
            sql = "Select level_number FROM levels WHERE player_id = ? AND completed = 0 ORDER BY level_number ASC LIMIT 1";
        }

        try {
            PreparedStatement stm = db.connection.prepareStatement(sql);
            stm.setInt(1,playerId);
            ResultSet rs = stm.executeQuery();
            if(rs.next())
                return rs.getInt("level_number");

        }
        catch (SQLException e)
        {
            e.printStackTrace();
        }

        System.out.println("You completed all level");
        return 4; // toate nivelurile au fost completate
    }

    public void updateTotalScore(String username,String password)
    {
        int playerId = getPlayerId(username,password);
        String selectSql = "SELECT SUM(score) AS totalScore FROM levels WHERE player_id = ? AND completed = 1";

        try {
            PreparedStatement selectStmt = db.connection.prepareStatement(selectSql);
            selectStmt.setInt(1, playerId);
            ResultSet rs = selectStmt.executeQuery();

            if (rs.next()) {
                int totalScore = rs.getInt("totalScore");

                // Pasul 2: Update scor total în tabela players
                String updateSql = "UPDATE players SET score = ? WHERE id = ?";
                PreparedStatement updateStmt = db.connection.prepareStatement(updateSql);
                updateStmt.setInt(1, totalScore);
                updateStmt.setInt(2, playerId);

                updateStmt.executeUpdate();

                System.out.println("Scorul total a fost actualizat la: " + totalScore);
            } else {
                System.out.println("Nu există scoruri de actualizat.");
            }
        } catch (SQLException e) {
            e.printStackTrace();
        }
    }

    public ArrayList<String> getScoreboard()
    {
        ArrayList <String> scoreboard = new ArrayList<>();
        int nr = 1;

        String sql = "";
        if(isOracleDatabase())
        {
            sql = "SELECT username, score FROM players ORDER BY score DESC FETCH FIRST 10 ROWS ONLY";

        }
        else {
            sql = "SELECT username,score FROM players ORDER BY score DESC LIMIT 10";
        }

        try {
        PreparedStatement stmt = db.connection.prepareStatement(sql);
        ResultSet rs = stmt.executeQuery();

        while (rs.next()) {
            String username = rs.getString("username");
            int score = rs.getInt("score");
            scoreboard.add(nr + ". " + username + "     -    Score: " + score);
            nr++;
        }

        } catch (SQLException e) {
            e.printStackTrace();
        }

        return scoreboard;

    }
}
