package PaooGame.Database;

import com.sun.security.jgss.GSSUtil;

import java.io.BufferedReader;
import java.io.FileReader;
import java.io.IOException;
import java.sql.*;
import java.util.concurrent.ExecutorService;
import java.util.concurrent.Executors;

public class Database {
    public DatabaseManager db;

    public Database(){
        this.db = DatabaseManager.getInstance();
    }
    public boolean connect(){

        if(db.connection != null){
            System.out.println("Connected already to the database !!!");
            return true;
        }

        return (db.connect() != null);
    }

    public boolean isConnected(){
        return (db.connection != null);
    }
    public void disconnect(){
//        db.disconnect();
        System.out.println("Disconnecting...");
        db.disconnect();
    }

    public int[][] loadCollisionMap1(int width , int height){
        String path = "res/maps/collision/map1.txt";

        int [][] map = new int[height][width];
        int [][] tiles=new int[width][height];
        String line;
        int row = 0;

        try {

            String sql =null;
            Statement stm = null;
//            sql = "DROP TABLE MAP1";

            stm = db.connection.createStatement();
            //stm.executeUpdate(sql);

            if(db.isOracleDatabase) {
                //mai intai stergem
                sql = "BEGIN " +
                        "   EXECUTE IMMEDIATE 'DROP TABLE CollisionMAP1'; " +
                        "EXCEPTION " +
                        "   WHEN OTHERS THEN " +
                        "      IF SQLCODE != -942 THEN RAISE; END IF; " +
                        "END;";
                stm.execute(sql);

                sql = "CREATE TABLE CollisionMAP1 " +
                        "(ID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY," +
                        "LINIE NUMBER NOT NULL,"
                        + "COLOANA NUMBER NOT NULL," +
                        "VALUE NUMBER NOT NULL)";
            }
            else{
                sql = "DROP TABLE IF EXISTS CollisionMAP1";
                stm.execute(sql);

                System.out.println("CollisionMAP1 Deleted !!!");
                sql = "CREATE TABLE IF NOT EXISTS CollisionMAP1 " +
                        "(ID INTEGER PRIMARY KEY AUTOINCREMENT," +
                        "LINIE INTEGER NOT NULL,"
                        + "COLOANA INTEGER NOT NULL," +
                        "VALUE INTEGER NOT NULL)";
            }
//            stm = db.connection.createStatement();
            int delay = 50000;
            while((delay--) !=0);

            stm.executeUpdate(sql);
            stm.close();
        }
        catch (SQLException e){
            System.out.println("Error creating MAP1 -> "+e.getMessage());
        }
        try {

//            System.out.println("Trying to open file with FileReader...");
            FileReader fr = new FileReader(path);
//            System.out.println("FileReader opened successfully.");
            BufferedReader reader = new BufferedReader(fr);

            while((line = reader.readLine()) != null && row <height){
                line = line.trim(); //elimina spatiile de la inceput si sfarsit
                if(line.isEmpty()) continue;

                String [] element = line.split("\\s+");
                for(int i=0;i<width;i++)
                {
                    map[row][i] = Integer.parseInt(element[i]);
                }

                row++;
            }
            for (int i = 0; i < height; i++) {
                for (int j = 0; j < width; j++) {
                    tiles[j][i] = map[i][j];
                }
            }

            reader.close();
        }
        catch (IOException e)
        {
            System.out.println("Text file ThematicMap couldn't be opened");
        }

        try{

            for(int i=0;i<map.length;i++){
                for(int j=0;j<map[i].length;j++){
                    String sql = "INSERT INTO CollisionMAP1 (LINIE,COLOANA,VALUE) VALUES ("+i+","+j+","+map[i][j]+")";
                    Statement stm = null;
                    stm = db.connection.createStatement();
                    stm.executeUpdate(sql);
                    stm.close();
                }
            }
        }catch (SQLException e){
            System.out.println("Error loading MAP1 -> "+e.getMessage());
        }
        return map;
    }
    public int[][] loadThematicMap1(int width , int height){
        String path = "res/maps/thematic/map1.txt";

        int [][] map = new int[height][width];
        int [][] tiles=new int[width][height];
        String line;
        int row = 0;

        try {
            String sql =null;
            Statement stm = null;
//            sql = "DROP TABLE MAP1";
//
            stm = db.connection.createStatement();
//            stm.executeUpdate(sql);
            if(db.isOracleDatabase) {
                sql = "BEGIN " +
                        "   EXECUTE IMMEDIATE 'DROP TABLE MAP1'; " +
                        "EXCEPTION " +
                        "   WHEN OTHERS THEN " +
                        "      IF SQLCODE != -942 THEN RAISE; END IF; " +
                        "END;";
                stm.execute(sql);

                sql = "CREATE TABLE MAP1 " +
                        "(ID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY," +
                        "LINIE NUMBER NOT NULL,"
                        + "COLOANA NUMBER NOT NULL," +
                        "VALUE NUMBER NOT NULL)";
            }
            else{
                sql = "DROP TABLE IF EXISTS MAP1";
                stm.execute(sql);

                sql = "CREATE TABLE IF NOT EXISTS MAP1 " +
                        "(ID INTEGER PRIMARY KEY AUTOINCREMENT," +
                        "LINIE INTEGER NOT NULL,"
                        + "COLOANA INTEGER NOT NULL," +
                        "VALUE INTEGER NOT NULL)";
            }
//            stm = db.connection.createStatement();
            int delay = 50000;
            while((delay--) !=0);

            stm.executeUpdate(sql);
            stm.close();
        }
        catch (SQLException e){
            System.out.println("Error creating MAP1 -> "+e.getMessage());
        }
        try {
//            System.out.println("Trying to open file with FileReader...");
            FileReader fr = new FileReader(path);
//            System.out.println("FileReader opened successfully.");
            BufferedReader reader = new BufferedReader(fr);

            while((line = reader.readLine()) != null && row <height){
                line = line.trim(); //elimina spatiile de la inceput si sfarsit
                if(line.isEmpty()) continue;

                String [] element = line.split("\\s+");
                for(int i=0;i<width;i++)
                {
                    map[row][i] = Integer.parseInt(element[i]);
                }

                row++;
            }
            for (int i = 0; i < height; i++) {
                for (int j = 0; j < width; j++) {
                    tiles[j][i] = map[i][j];
                }
            }

            reader.close();
        }
        catch (IOException e)
        {
            System.out.println("Text file ThematicMap couldn't be opened");
        }

        try{
            for(int i=0;i<map.length;i++){
                for(int j=0;j<map[i].length;j++){
                    String sql = "INSERT INTO MAP1 (LINIE,COLOANA,VALUE) VALUES ("+i+","+j+","+map[i][j]+")";
                    Statement stm = null;
                    stm = db.connection.createStatement();
                    stm.executeUpdate(sql);
                    stm.close();
                }
            }
        }catch (SQLException e){
            System.out.println("Error loading MAP1 -> "+e.getMessage());
        }
        return map;
    }
    public boolean isOracleDatabase(){
        return db.isOracleDatabase;
    }
    public int[][] downloadCollisionMap1(){
        int height=0,width=0;
        try(Statement stmt = db.connection.createStatement()){
            System.out.println("Downloading CollisionMAP1 from database...");
            String querySize = "SELECT MAX(LINIE) AS maxLine , MAX(COLOANA) AS maxCol FROM MAP1 ";
            try (ResultSet rs = stmt.executeQuery(querySize)) {
                if (rs.next()) {
                    height = rs.getInt("maxLine") + 1;
                    width = rs.getInt("maxCol") + 1;
                }
            }

            int[][] map = new int[height][width];
            String query = "SELECT LINIE,COLOANA , VALUE FROM CollisionMAP1";
            try (ResultSet rs = stmt.executeQuery(query)) {
                while (rs.next()) {
                    int linie = rs.getInt("LINIE");
                    int coloana = rs.getInt("COLOANA");
                    int value = rs.getInt("VALUE");
                    map[linie][coloana] = value;
                }
            }
            return map;

        }catch (SQLException e){
            e.printStackTrace();
            return null;
        }
    }
    public int[][] downloadThematicMap1(){
        int height=0,width=0;
        try(Statement stmt = db.connection.createStatement()){
            System.out.println("Downloading MAP1 from database...");
            String querySize = "SELECT MAX(LINIE) AS maxLine , MAX(COLOANA) AS maxCol FROM MAP1 ";
            try (ResultSet rs = stmt.executeQuery(querySize)) {
                if (rs.next()) {
                    height = rs.getInt("maxLine") + 1;
                    width = rs.getInt("maxCol") + 1;
                }
            }

            int[][] map = new int[height][width];
            String query = "SELECT LINIE,COLOANA , VALUE FROM MAP1";
            try (ResultSet rs = stmt.executeQuery(query)) {
                while (rs.next()) {
                    int linie = rs.getInt("LINIE");
                    int coloana = rs.getInt("COLOANA");
                    int value = rs.getInt("VALUE");
                    map[linie][coloana] = value;
                }
            }
            return map;

        }catch (SQLException e){
            e.printStackTrace();
            return null;
        }
    }
    public void deleteMap() {


    }
}
